# Site
title:              Burhan Bilen
bio:                "Hi there, I'm Burhan. I'm a Full Stack Software Developer. Currently, I'm working as Data Analytics & Automation Developer at Nokia."
description:        "Hi there, I'm Burhan. I'm a Full Stack Software Developer. Currently, I'm working as Data Analytics & Automation Developer at Nokia."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://burhanbilen.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..5
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   burhanbilen

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              burhan.bilenn@gmail.com
#twitter:            username
#facebook:           username
github-url:         burhanbilen
stackoverflow:     9160757/burhan-bilen
linkedin:          burhanbilen
#xing:              username
#instagram:          username
scholar:            citations?user=aQUTLs4AAAAJ&hl=tr
#lastfm:            username
#tumblr:            username
medium:            '@burhanbilen'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
